/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-10-26 00:54:54
 */


#ifndef CONNECTIVITYWLAN_WLAN_H
#define CONNECTIVITYWLAN_WLAN_H

#include <BCDS_Retcode.h>


/**
 * Sets up the WLAN.
 */
Retcode_T ConnectivityWLANTheNetwork_Setup(void);

/**
 * Enables the WLAN sensor.
 */
Retcode_T ConnectivityWLANTheNetwork_Enable(void);



#endif
