/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-10-26 00:54:54
 */


#ifndef CONNECTIVITYHTTPRESTCLIENT_HTTPRESTCLIENT_H
#define CONNECTIVITYHTTPRESTCLIENT_HTTPRESTCLIENT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the HttpRestClient.
 */
Retcode_T ConnectivityHttpRestClientHttpBackEnd_Setup(void);

/**
 * Enables the HttpRestClient sensor.
 */
Retcode_T ConnectivityHttpRestClientHttpBackEnd_Enable(void);

/**
 * Provides read access to post.
 */
Retcode_T ConnectivityHttpRestClientHttpBackEnd_Post_Read(char** result);

/**
 * Provides write access to post.
 */
Retcode_T ConnectivityHttpRestClientHttpBackEnd_Post_Write(char** result);


#endif
