/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-10-26 00:54:54
 */


#include <FreeRTOS.h>
#include <BCDS_Basics.h>
#include <BCDS_CmdProcessor.h>
#include <timers.h>
#include <BCDS_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery30Second1;

static void InternalHandleEvery30Second1(TimerHandle_t xTimer)
{
	BCDS_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery30Second1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	
	timerHandleEvery30Second1 = xTimerCreate("timerHandleEvery30Second1", UINT32_C(30000), pdTRUE, NULL, InternalHandleEvery30Second1);
	
	if(timerHandleEvery30Second1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery30Second1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery30Second1_Enable(void)
{
	xTimerStart(timerHandleEvery30Second1, 0);
	
	return NO_EXCEPTION;
}


