/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-10-26 00:54:54
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <BCDS_LightSensor.h>
#include <XdkSensorHandle.h>
#include "MitaExceptions.h"


Retcode_T SensorLight_Setup(void)
{
	Retcode_T exception = RETCODE_OK;
	
	exception = LightSensor_init(xdkLightSensor_MAX44009_Handle);
	if(exception != NO_EXCEPTION) return exception;
	
	// Configure manual mode, brightness and integration time
	exception = LightSensor_setManualMode(xdkLightSensor_MAX44009_Handle, LIGHTSENSOR_MAX44009_ENABLE_MODE);
	if(exception != NO_EXCEPTION) return exception;
	exception = LightSensor_setBrightness(xdkLightSensor_MAX44009_Handle, LIGHTSENSOR_NORMAL_BRIGHTNESS);
	if(exception != NO_EXCEPTION) return exception;
	exception = LightSensor_setIntegrationTime(xdkLightSensor_MAX44009_Handle, LIGHTSENSOR_800_MS);
	if(exception != NO_EXCEPTION) return exception;
	
	// Configure continuous mode
	exception = LightSensor_setContinuousMode(xdkLightSensor_MAX44009_Handle, LIGHTSENSOR_MAX44009_DISABLE_MODE);
	if(exception != NO_EXCEPTION) return exception;
	
	return NO_EXCEPTION;
}

Retcode_T SensorLight_Enable(void)
{
	
	return NO_EXCEPTION;
}


