/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-10-26 00:54:54
 */


#ifndef SENSORENVIRONMENT_ENVIRONMENT_H
#define SENSORENVIRONMENT_ENVIRONMENT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the environment.
 */
Retcode_T SensorEnvironment_Setup(void);

/**
 * Enables the environment sensor.
 */
Retcode_T SensorEnvironment_Enable(void);



#endif
